'use client';
import { useState } from 'react'; import { useRouter, useSearchParams } from 'next/navigation';
export default function NewAccountForm(){ const [org,setOrg]=useState(''); const [mode,setMode]=useState('providers'); const [form,setForm]=useState({email:'',password:'',imapHost:'',imapPort:993,smtpHost:'',smtpPort:465,imapSecure:true,smtpSecure:true}); const [msg,setMsg]=useState(''); const [busy,setBusy]=useState(false); const router=useRouter(); const search=useSearchParams(); const error=search.get('error');
 function connect(p){ if(!org.trim()) return setMsg('اكتب اسم الجمعية اول'); window.location.href=`/api/connect/${p}?organizationName=${encodeURIComponent(org.trim())}` }
 function set(k,v){setForm(x=>({...x,[k]:v}))}
 async function test(){setBusy(true);setMsg('');const r=await fetch('/api/accounts/test',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(form)});const d=await r.json();setBusy(false);setMsg(r.ok?'تم الاتصال بنجاح':d.error)}
 async function save(e){e.preventDefault();setBusy(true);setMsg('');const r=await fetch('/api/accounts',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({...form,organizationName:org})});const d=await r.json();setBusy(false);if(!r.ok)return setMsg(d.error);router.push(`/mail/${d.account.id}`)}
 return <section className="connect-card"><label>اسم الجمعية</label><input value={org} onChange={e=>setOrg(e.target.value)} placeholder="مثال جمعية حفظ النعمة"/>{(error||msg)&&<p className="error">{error||msg}</p>}
 {mode==='providers'?<div className="provider-list"><button onClick={()=>connect('google')}><b>Google</b><span>Gmail وGoogle Workspace</span></button><button onClick={()=>connect('microsoft')}><b>Microsoft</b><span>Outlook وHotmail وMicrosoft 365</span></button><button onClick={()=>connect('zoho')}><b>Zoho</b><span>ربط حساب Zoho Mail</span></button><button onClick={()=>setMode('custom')}><b>بريد مخصص</b><span>IMAP وSMTP</span></button></div>:<form className="custom-form" onSubmit={save}><div className="grid-2"><div><label>البريد</label><input type="email" dir="ltr" value={form.email} onChange={e=>set('email',e.target.value)} required/></div><div><label>كلمة المرور او App Password</label><input type="password" value={form.password} onChange={e=>set('password',e.target.value)} required/></div><div><label>خادم IMAP</label><input dir="ltr" value={form.imapHost} onChange={e=>set('imapHost',e.target.value)} placeholder="imap.example.com" required/></div><div><label>منفذ IMAP</label><input type="number" value={form.imapPort} onChange={e=>set('imapPort',e.target.value)}/></div><div><label>خادم SMTP</label><input dir="ltr" value={form.smtpHost} onChange={e=>set('smtpHost',e.target.value)} placeholder="smtp.example.com" required/></div><div><label>منفذ SMTP</label><input type="number" value={form.smtpPort} onChange={e=>set('smtpPort',e.target.value)}/></div></div><div className="form-actions"><button type="button" className="button ghost" onClick={()=>setMode('providers')}>رجوع</button><button type="button" className="button ghost" onClick={test} disabled={busy}>اختبار الاتصال</button><button className="button primary" disabled={busy}>حفظ البريد</button></div></form>}
 </section> }
